spring:
  mvc:
    static-path-pattern: /**/*.*
    throw-exception-if-no-handler-found: true
  web:
    resources:
      static-locations: classpath:/static/
server:
  compression:
    enabled: true
    mime-types:
      - text/javascript
      - text/css
      - application/javascript
      - application/css
      - application/json

